In [546]:
import pandas as pd # for data manipulation
import numpy as np # for data manipulation

from sklearn.model_selection import train_test_split # for splitting the data into train and test samples
from sklearn.metrics import classification_report # for model evaluation metrics
from sklearn.preprocessing import OrdinalEncoder # for encoding categorical features from strings to number arrays

from sklearn.naive_bayes import GaussianNB


In [547]:
df = pd.read_csv('/Users/navamongkoltongta/OneDrive - Assumption University/Year2.2/Data Science/Project/vgsales.csv')

In [548]:
df.drop(columns=['NA_Sales','EU_Sales','JP_Sales','Other_Sales'], inplace=True)

In [549]:
df.count()

Rank            16598
Name            16598
Platform        16598
Year            16327
Genre           16598
Publisher       16540
Global_Sales    16598
dtype: int64

In [550]:
df.dropna(how='any',subset=['Year','Publisher'],inplace=True)

In [551]:
df[df['Publisher'].isnull()]

Empty DataFrame
Columns: [Rank, Name, Platform, Year, Genre, Publisher, Global_Sales]
Index: []

In [552]:
df.isnull().sum()

Rank            0
Name            0
Platform        0
Year            0
Genre           0
Publisher       0
Global_Sales    0
dtype: int64

In [553]:
df.count()

Rank            16291
Name            16291
Platform        16291
Year            16291
Genre           16291
Publisher       16291
Global_Sales    16291
dtype: int64

In [554]:
df.describe()

Rank          Year  Global_Sales
count  16291.000000  16291.000000  16291.000000
mean    8290.190228   2006.405561      0.540910
std     4792.654450      5.832412      1.567345
min        1.000000   1980.000000      0.010000
25%     4132.500000   2003.000000      0.060000
50%     8292.000000   2007.000000      0.170000
75%    12439.500000   2010.000000      0.480000
max    16600.000000   2020.000000     82.740000

In [555]:
# df['Mean_global']=df['Global_Sales'].apply(lambda x: 'High' if x>=0.5377441 else 'Low')
# dfhigh.loc[dfhigh['Global_Sales'] > 1, 'Test'] = 2
# dfhigh.loc[0.5377441 < dfhigh['Global_Sales'] >= 1, 'Test'] = 1
df.loc[df['Global_Sales'].between(10.0,100), 'Sales_level'] = 3
df.loc[df['Global_Sales'].between(1,9.9), 'Sales_level'] = 2
df.loc[df['Global_Sales'].between(0.5377441,0.999), 'Sales_level'] = 1
df.loc[df['Global_Sales'] < 0.5377441, 'Sales_level'] = 0

# dfhigh.loc[dfhigh['Global_Sales'] == 'Action', 'GenreId'] = 1 
df.sample(5)


Rank                             Name Platform    Year         Genre  \
10756  10758                      Wasteland 2       PC  2015.0  Role-Playing   
15670  15673                            NEVES       DS  2007.0        Puzzle   
8145    8147  Atari Anniversary Edition Redux       PS  2000.0          Misc   
2739    2741                            Turok     X360  2008.0        Action   
1887    1889                  Dante's Inferno      PS3  2010.0        Action   

                    Publisher  Global_Sales  Sales_level  
10756    inXile Entertainment          0.10          0.0  
15670  Ignition Entertainment          0.02          0.0  
8145               Infogrames          0.18          0.0  
2739               Touchstone          0.75          1.0  
1887          Electronic Arts          1.09          2.0

In [556]:
# dfhigh = df.loc[df['Mean_global'] == 'High']
# dfhigh.head(5)

In [557]:
df.Genre.value_counts()

Action          3251
Sports          2304
Misc            1686
Role-Playing    1470
Shooter         1282
Adventure       1274
Racing          1225
Platform         875
Simulation       848
Fighting         836
Strategy         670
Puzzle           570
Name: Genre, dtype: int64

In [558]:
df.Platform.value_counts()

DS      2131
PS2     2127
PS3     1304
Wii     1290
X360    1234
PSP     1197
PS      1189
PC       938
XB       803
GBA      786
GC       542
3DS      499
PSV      410
PS4      336
N64      316
SNES     239
XOne     213
SAT      173
WiiU     143
2600     116
NES       98
GB        97
DC        52
GEN       27
NG        12
SCD        6
WS         6
3DO        3
TG16       2
GG         1
PCFX       1
Name: Platform, dtype: int64

In [559]:
df.loc[df['Platform'] == 'DS', 'PlatformId'] = 1 
df.loc[df['Platform'] == 'PS2', 'PlatformId'] = 2
df.loc[df['Platform'] == 'PS3', 'PlatformId'] = 3 
df.loc[df['Platform'] == 'Wii', 'PlatformId'] = 4 
df.loc[df['Platform'] == 'X360', 'PlatformId'] = 5 
df.loc[df['Platform'] == 'PSP', 'PlatformId'] = 6 
df.loc[df['Platform'] == 'PS', 'PlatformId'] = 7 
df.loc[df['Platform'] == 'PC', 'PlatformId'] = 8 
df.loc[df['Platform'] == 'XB', 'PlatformId'] = 9
df.loc[df['Platform'] == 'GBA', 'PlatformId'] = 10
df.loc[df['Platform'] == 'GC', 'PlatformId'] = 11
df.loc[df['Platform'] == '3DS', 'PlatformId'] = 12
df.loc[df['Platform'] == 'PSV', 'PlatformId'] = 13
df.loc[df['Platform'] == 'PS4', 'PlatformId'] = 14
df.loc[df['Platform'] == 'N64', 'PlatformId'] = 15
df.loc[df['Platform'] == 'SNES', 'PlatformId'] = 16
df.loc[df['Platform'] == 'XOne', 'PlatformId'] = 17
df.loc[df['Platform'] == 'SAT', 'PlatformId'] = 18
df.loc[df['Platform'] == 'WiiU', 'PlatformId'] = 19
df.loc[df['Platform'] == '2600', 'PlatformId'] = 20
df.loc[df['Platform'] == 'NES', 'PlatformId'] = 21
df.loc[df['Platform'] == 'GB', 'PlatformId'] = 22
df.loc[df['Platform'] == 'DC', 'PlatformId'] = 23
df.loc[df['Platform'] == 'GEN', 'PlatformId'] = 24
df.loc[df['Platform'] == 'NG', 'PlatformId'] = 25
df.loc[df['Platform'] == 'SCD', 'PlatformId'] = 26
df.loc[df['Platform'] == 'WS', 'PlatformId'] = 27
df.loc[df['Platform'] == '3DO', 'PlatformId'] = 28
df.loc[df['Platform'] == 'TG16', 'PlatformId'] = 39
df.loc[df['Platform'] == 'GG', 'PlatformId'] = 30
df.loc[df['Platform'] == 'PCFX', 'PlatformId'] = 31

df.sample(10)


Rank                                               Name Platform  \
4507    4509                              NiGHTS into dreams...      SAT   
3634    3636                        Sly Cooper: Thieves in Time      PS3   
16200  16203                                       Hyakka Yakou      PSV   
243      244             Uncharted: The Nathan Drake Collection      PS4   
13853  13855              Klonoa Heroes: Densetsu no Star Medal      GBA   
4586    4588                     Tony Hawk's American Wasteland       GC   
12646  12648  NTRA Breeders' Cup World Thoroughbred Champion...       XB   
4506    4508                                   Wheel of Fortune       DS   
15023  15026                   Brothers in Arms: Hell's Highway       PC   
3082    3084                        Shrek: Hassle at the Castle      GBA   

         Year         Genre                           Publisher  Global_Sales  \
4507   1996.0      Platform                                Sega          0.43   
3634   2013.0      Platform  Sony Computer Entertainment Europe          0.55   
16200  2015.0        Action                             Unknown          0.01   
243    2015.0        Action         Sony Computer Entertainment          4.47   
13853  2002.0  Role-Playing                  Namco Bandai Games          0.04   
4586   2005.0        Sports                          Activision          0.42   
12646  2005.0    Simulation                  Bethesda Softworks          0.06   
4506   2010.0          Misc                                 THQ          0.43   
15023  2008.0       Shooter                             Ubisoft          0.02   
3082   2002.0        Action                      TDK Mediactive          0.66   

       Sales_level  PlatformId  
4507           0.0        18.0  
3634           1.0         3.0  
16200          0.0        13.0  
243            2.0        14.0  
13853          0.0        10.0  
4586           0.0        11.0  
12646          0.0         9.0  
4506           0.0         1.0  
15023          0.0         8.0  
3082           1.0        10.0

In [560]:
df.loc[df['Genre'] == 'Action', 'GenreId'] = 1 
df.loc[df['Genre'] == 'Sports', 'GenreId'] = 2
df.loc[df['Genre'] == 'Shooter', 'GenreId'] = 3 
df.loc[df['Genre'] == 'Role-Playing', 'GenreId'] = 4 
df.loc[df['Genre'] == 'Misc', 'GenreId'] = 5 
df.loc[df['Genre'] == 'Racing', 'GenreId'] = 6 
df.loc[df['Genre'] == 'Platform', 'GenreId'] = 7 
df.loc[df['Genre'] == 'Fighting', 'GenreId'] = 8 
df.loc[df['Genre'] == 'Simulation', 'GenreId'] = 9 
df.loc[df['Genre'] == 'Puzzle', 'GenreId'] = 10 
df.loc[df['Genre'] == 'Adventure', 'GenreId'] = 11 
df.loc[df['Genre'] == 'Strategy', 'GenreId'] = 12 

df.sample(10)



Rank                                        Name Platform    Year  \
8852    8854                       J-League Victory Goal      SAT  1995.0   
10774  10776        InuYasha: Secret of the Divine Jewel       DS  2007.0   
10116  10118                   Just In Time Translations       DS  2009.0   
163      164                   Mario Kart: Super Circuit      GBA  2001.0   
15825  15828                            Puyo Puyo Tetris     WiiU  2014.0   
7089    7091          Disney Princess: Enchanted Journey      PS2  2007.0   
14970  14973  Strike Witches 2: Iyasu Naosu Punipunisuru       DS  2010.0   
8458    8460                                  Death Trap     2600  1982.0   
10921  10923          Dragon Ball Kai: Ultimate Butouden       DS  2011.0   
4381    4383                          SingStar Take That      PS2  2009.0   

              Genre                    Publisher  Global_Sales  Sales_level  \
8852         Sports                         Sega          0.15          0.0   
10774  Role-Playing           Namco Bandai Games          0.10          0.0   
10116          Misc                          THQ          0.11          0.0   
163          Racing                     Nintendo          5.47          2.0   
15825        Puzzle                         Sega          0.02          0.0   
7089      Adventure   Disney Interactive Studios          0.23          0.0   
14970        Action              Kadokawa Shoten          0.02          0.0   
8458         Action           Avalon Interactive          0.17          0.0   
10921      Fighting           Namco Bandai Games          0.09          0.0   
4381           Misc  Sony Computer Entertainment          0.45          0.0   

       PlatformId  GenreId  
8852         18.0      2.0  
10774         1.0      4.0  
10116         1.0      5.0  
163          10.0      6.0  
15825        19.0     10.0  
7089          2.0     11.0  
14970         1.0      1.0  
8458         20.0      1.0  
10921         1.0      8.0  
4381          2.0      5.0

In [561]:
inputs = df.drop('Sales_level',axis='columns')
target = df.Sales_level

In [562]:
# inputs = pd.concat([inputs,GenreId],axis='columns')
# inputs.head(5)


In [563]:
inputs.drop(['Rank','Name','Platform','Publisher','Genre','Global_Sales'],axis='columns',inplace=True)
inputs.head()

Year  PlatformId  GenreId
0  2006.0         4.0      2.0
1  1985.0        21.0      7.0
2  2008.0         4.0      6.0
3  2009.0         4.0      2.0
4  1996.0        22.0      4.0

In [564]:
X = inputs.astype(int)
Y = target.astype(int)
X_train, X_test, y_train, y_test = train_test_split(X,Y,test_size=0.5)
model = GaussianNB()

In [565]:
X_test[0:10]

Year  PlatformId  GenreId
10371  2009           1        2
2065   2008           3        3
51     2008           5        1
10466  2001           2       11
6721   2002           2        2
14242  2010           4        6
6951   2007           2        6
5616   2014           5        3
14561  2011           6        5
11646  2009           1        9

In [566]:
model.fit(X_train,y_train)

GaussianNB()

In [567]:
model.score(X_test,y_test)

0.7647925362140928

In [568]:
model.predict(X_test[0:10])

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [569]:
model.predict_proba(X_test[:10])

array([[7.81967577e-01, 1.09677431e-01, 1.03721814e-01, 4.63317699e-03],
       [7.88919841e-01, 1.07282530e-01, 9.92914606e-02, 4.50616780e-03],
       [7.99296934e-01, 1.06114517e-01, 9.14866877e-02, 3.10186133e-03],
       [8.84701214e-01, 5.80289392e-02, 5.65463588e-02, 7.23488454e-04],
       [7.29986777e-01, 1.26826667e-01, 1.38368333e-01, 4.81822364e-03],
       [8.22022156e-01, 9.12319154e-02, 8.30303910e-02, 3.71553718e-03],
       [8.10827738e-01, 9.38343975e-02, 9.12524888e-02, 4.08537534e-03],
       [7.76436135e-01, 1.13785254e-01, 1.05036488e-01, 4.74212301e-03],
       [8.07477870e-01, 9.77637943e-02, 9.06527851e-02, 4.10555035e-03],
       [8.73611364e-01, 6.55490723e-02, 5.90592932e-02, 1.78027074e-03]])

In [570]:
from sklearn.model_selection import cross_val_score
cross_val_score(GaussianNB(),X_train, y_train, cv=5)

array([0.75567833, 0.75936157, 0.74953959, 0.75997545, 0.76365869])