In [1083]:
#import
import pandas as pd
import numpy as np

from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report
from sklearn.preprocessing import OrdinalEncoder

from sklearn.naive_bayes import GaussianNB


In [1084]:
#read_csv
df = pd.read_csv('/Users/navamongkoltongta/OneDrive - Assumption University/Year2.2/Data Science/Project/vgsales.csv')

In [1085]:
#drop_unneccessary_column
df.drop(columns=['NA_Sales','EU_Sales','JP_Sales','Other_Sales'], inplace=True)

In [1086]:
df.count()

Rank            16598
Name            16598
Platform        16598
Year            16327
Genre           16598
Publisher       16540
Global_Sales    16598
dtype: int64

In [1087]:
df.dropna(how='any',subset=['Year','Publisher'],inplace=True)

In [1088]:
df[df['Publisher'].isnull()]

Empty DataFrame
Columns: [Rank, Name, Platform, Year, Genre, Publisher, Global_Sales]
Index: []

In [1089]:
df.isnull().sum()

Rank            0
Name            0
Platform        0
Year            0
Genre           0
Publisher       0
Global_Sales    0
dtype: int64

In [1090]:
df.count()

Rank            16291
Name            16291
Platform        16291
Year            16291
Genre           16291
Publisher       16291
Global_Sales    16291
dtype: int64

In [1091]:
df.describe()

Rank          Year  Global_Sales
count  16291.000000  16291.000000  16291.000000
mean    8290.190228   2006.405561      0.540910
std     4792.654450      5.832412      1.567345
min        1.000000   1980.000000      0.010000
25%     4132.500000   2003.000000      0.060000
50%     8292.000000   2007.000000      0.170000
75%    12439.500000   2010.000000      0.480000
max    16600.000000   2020.000000     82.740000

In [1092]:
#create new column level of global sales
df.loc[df['Global_Sales'].between(10.0,100), 'Sales_level'] = 3
df.loc[df['Global_Sales'].between(1,9.9), 'Sales_level'] = 2
df.loc[df['Global_Sales'].between(0.5377441,0.999), 'Sales_level'] = 1
df.loc[df['Global_Sales'] < 0.5377441, 'Sales_level'] = 0

df.head(5)


Rank                      Name Platform    Year         Genre Publisher  \
0     1                Wii Sports      Wii  2006.0        Sports  Nintendo   
1     2         Super Mario Bros.      NES  1985.0      Platform  Nintendo   
2     3            Mario Kart Wii      Wii  2008.0        Racing  Nintendo   
3     4         Wii Sports Resort      Wii  2009.0        Sports  Nintendo   
4     5  Pokemon Red/Pokemon Blue       GB  1996.0  Role-Playing  Nintendo   

   Global_Sales  Sales_level  
0         82.74          3.0  
1         40.24          3.0  
2         35.82          3.0  
3         33.00          3.0  
4         31.37          3.0

In [1093]:
#See all Genre
df.Genre.value_counts()

Action          3251
Sports          2304
Misc            1686
Role-Playing    1470
Shooter         1282
Adventure       1274
Racing          1225
Platform         875
Simulation       848
Fighting         836
Strategy         670
Puzzle           570
Name: Genre, dtype: int64

In [1094]:
#See all Platform
df.Platform.value_counts()

DS      2131
PS2     2127
PS3     1304
Wii     1290
X360    1234
PSP     1197
PS      1189
PC       938
XB       803
GBA      786
GC       542
3DS      499
PSV      410
PS4      336
N64      316
SNES     239
XOne     213
SAT      173
WiiU     143
2600     116
NES       98
GB        97
DC        52
GEN       27
NG        12
SCD        6
WS         6
3DO        3
TG16       2
GG         1
PCFX       1
Name: Platform, dtype: int64

In [1095]:
#Sort platform to num
df.loc[df['Platform'] == 'DS', 'PlatformId'] = 1 
df.loc[df['Platform'] == 'PS2', 'PlatformId'] = 2
df.loc[df['Platform'] == 'PS3', 'PlatformId'] = 3 
df.loc[df['Platform'] == 'Wii', 'PlatformId'] = 4 
df.loc[df['Platform'] == 'X360', 'PlatformId'] = 5 
df.loc[df['Platform'] == 'PSP', 'PlatformId'] = 6 
df.loc[df['Platform'] == 'PS', 'PlatformId'] = 7 
df.loc[df['Platform'] == 'PC', 'PlatformId'] = 8 
df.loc[df['Platform'] == 'XB', 'PlatformId'] = 9
df.loc[df['Platform'] == 'GBA', 'PlatformId'] = 10
df.loc[df['Platform'] == 'GC', 'PlatformId'] = 11
df.loc[df['Platform'] == '3DS', 'PlatformId'] = 12
df.loc[df['Platform'] == 'PSV', 'PlatformId'] = 13
df.loc[df['Platform'] == 'PS4', 'PlatformId'] = 14
df.loc[df['Platform'] == 'N64', 'PlatformId'] = 15
df.loc[df['Platform'] == 'SNES', 'PlatformId'] = 16
df.loc[df['Platform'] == 'XOne', 'PlatformId'] = 17
df.loc[df['Platform'] == 'SAT', 'PlatformId'] = 18
df.loc[df['Platform'] == 'WiiU', 'PlatformId'] = 19
df.loc[df['Platform'] == '2600', 'PlatformId'] = 20
df.loc[df['Platform'] == 'NES', 'PlatformId'] = 21
df.loc[df['Platform'] == 'GB', 'PlatformId'] = 22
df.loc[df['Platform'] == 'DC', 'PlatformId'] = 23
df.loc[df['Platform'] == 'GEN', 'PlatformId'] = 24
df.loc[df['Platform'] == 'NG', 'PlatformId'] = 25
df.loc[df['Platform'] == 'SCD', 'PlatformId'] = 26
df.loc[df['Platform'] == 'WS', 'PlatformId'] = 27
df.loc[df['Platform'] == '3DO', 'PlatformId'] = 28
df.loc[df['Platform'] == 'TG16', 'PlatformId'] = 39
df.loc[df['Platform'] == 'GG', 'PlatformId'] = 30
df.loc[df['Platform'] == 'PCFX', 'PlatformId'] = 31

df.sample(10)


Rank                                               Name Platform  \
219      220                                            FIFA 15      PS3   
676      678                          WWE SmackDown vs Raw 2008      PS2   
3920    3922                      Disgaea 3: Absence of Justice      PS3   
13268  13270  Venus & Braves: Majo to Megami to Horobi no Yogen      PSP   
14659  14662                                          Fireblade       GC   
15753  15756                    Memories Off: Yubikiri no Kikou      PSP   
9539    9541                     Monster Hunter Frontier Online     X360   
8395    8397            The Naked Brothers Band: The Video Game      PS2   
1155    1157         Dragon Quest V: Hand of the Heavenly Bride       DS   
16336  16339            Nakayoshi All-Stars: Mezase Gakuen Idol       DS   

         Year         Genre           Publisher  Global_Sales  Sales_level  \
219    2014.0        Sports     Electronic Arts          4.82          2.0   
676    2007.0      Fighting                 THQ          2.34          2.0   
3920   2008.0  Role-Playing         Square Enix          0.51          0.0   
13268  2011.0  Role-Playing  Namco Bandai Games          0.05          0.0   
14659  2002.0        Action        Midway Games          0.03          0.0   
15753  2011.0     Adventure                 5pb          0.02          0.0   
9539   2010.0  Role-Playing              Capcom          0.13          0.0   
8395   2008.0          Misc                 THQ          0.17          0.0   
1155   2008.0  Role-Playing         Square Enix          1.60          2.0   
16336  2008.0          Misc       Creative Core          0.01          0.0   

       PlatformId  
219           3.0  
676           2.0  
3920          3.0  
13268         6.0  
14659        11.0  
15753         6.0  
9539          5.0  
8395          2.0  
1155          1.0  
16336         1.0

In [1096]:
#Sort Genre to num
df.loc[df['Genre'] == 'Action', 'GenreId'] = 1 
df.loc[df['Genre'] == 'Sports', 'GenreId'] = 2
df.loc[df['Genre'] == 'Shooter', 'GenreId'] = 3 
df.loc[df['Genre'] == 'Role-Playing', 'GenreId'] = 4 
df.loc[df['Genre'] == 'Misc', 'GenreId'] = 5 
df.loc[df['Genre'] == 'Racing', 'GenreId'] = 6 
df.loc[df['Genre'] == 'Platform', 'GenreId'] = 7 
df.loc[df['Genre'] == 'Fighting', 'GenreId'] = 8 
df.loc[df['Genre'] == 'Simulation', 'GenreId'] = 9 
df.loc[df['Genre'] == 'Puzzle', 'GenreId'] = 10 
df.loc[df['Genre'] == 'Adventure', 'GenreId'] = 11 
df.loc[df['Genre'] == 'Strategy', 'GenreId'] = 12 

df.sample(10)



Rank                       Name Platform    Year         Genre  \
10846  10848     Medieval II: Total War       PC  2006.0      Strategy   
4161    4163           Gauntlet Legends       PS  2000.0        Action   
5963    5965                       NieR     X360  2010.0  Role-Playing   
3360    3362      Mickey's Speedway USA      N64  2000.0        Racing   
15105  15108    Frontlines: Fuel of War       PC  2008.0       Shooter   
5183    5185    Tiger Woods PGA Tour 14     X360  2013.0        Sports   
3144    3146     GoldenEye: Rogue Agent      PS2  2004.0       Shooter   
4727    4729                    Dig Dug      NES  1985.0        Puzzle   
10086  10088  Skylanders: SuperChargers      3DS  2015.0        Action   
14211  14214                    RACE On       PC  2009.0        Racing   

                Publisher  Global_Sales  Sales_level  PlatformId  GenreId  
10846                Sega          0.09          0.0         8.0     12.0  
4161         Midway Games          0.47          0.0         7.0      1.0  
5963          Square Enix          0.29          0.0         5.0      4.0  
3360             Nintendo          0.60          1.0        15.0      6.0  
15105                 THQ          0.02          0.0         8.0      3.0  
5183      Electronic Arts          0.36          0.0         5.0      2.0  
3144      Electronic Arts          0.64          1.0         2.0      3.0  
4727   Namco Bandai Games          0.41          0.0        21.0     10.0  
10086          Activision          0.11          0.0        12.0      1.0  
14211   bitComposer Games          0.03          0.0         8.0      6.0

In [1097]:
#Define X and Y
inputs = df.drop('Sales_level',axis='columns')
target = df.Sales_level

In [1098]:
#Drop unused column
inputs.drop(['Year','Rank','Name','Platform','Publisher','Genre','Global_Sales'],axis='columns',inplace=True)
inputs.head()

PlatformId  GenreId
0         4.0      2.0
1        21.0      7.0
2         4.0      6.0
3         4.0      2.0
4        22.0      4.0

In [1099]:
#Define X and Y
X = inputs.astype(int)
Y = target.astype(int)
X_train, X_test, y_train, y_test = train_test_split(X,Y,test_size=0.3)
model = GaussianNB()

In [1100]:
X_test[0:10]

PlatformId  GenreId
6096            7        2
11635           4        1
12979           1        9
14635           8       12
11964           2        1
3310            4        5
5631            7        7
6934            9        2
14794           8        1
14265           8       12

In [1101]:
model.fit(X_train,y_train)

GaussianNB()

In [1102]:
model.score(X_test,y_test)

0.7696399345335515

In [1103]:
model.predict(X_test[0:10])

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [1104]:
model.predict_proba(X_test[:10])

array([[7.48056995e-01, 1.26304018e-01, 1.22451113e-01, 3.18787370e-03],
       [7.55450234e-01, 1.27948255e-01, 1.13927090e-01, 2.67442049e-03],
       [8.46654823e-01, 7.47060747e-02, 7.62607718e-02, 2.37833068e-03],
       [9.24799821e-01, 3.95128327e-02, 3.50295724e-02, 6.57773710e-04],
       [7.49836032e-01, 1.28283828e-01, 1.18925340e-01, 2.95480006e-03],
       [7.66741525e-01, 1.15240133e-01, 1.14319353e-01, 3.69898887e-03],
       [8.03064181e-01, 9.55290160e-02, 9.83196885e-02, 3.08711435e-03],
       [7.39962904e-01, 1.23964689e-01, 1.32514779e-01, 3.55762842e-03],
       [7.51013384e-01, 1.24997461e-01, 1.21168811e-01, 2.82034476e-03],
       [9.24799821e-01, 3.95128327e-02, 3.50295724e-02, 6.57773710e-04]])

In [1105]:
from sklearn.model_selection import cross_val_score
cross_val_score(GaussianNB(),X_train, y_train, cv=5)

array([0.76983779, 0.76939939, 0.76852258, 0.77017544, 0.77324561])