In [610]:
#import
import pandas as pd
import numpy as np

from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report
from sklearn.preprocessing import OrdinalEncoder

from sklearn.naive_bayes import GaussianNB


In [611]:
#read_csv
df = pd.read_csv('/Users/navamongkoltongta/OneDrive - Assumption University/Year2.2/Data Science/Project/vgsales.csv')

In [612]:
#drop_unneccessary_column
df.drop(columns=['NA_Sales','EU_Sales','JP_Sales','Other_Sales'], inplace=True)

In [613]:
df.count()

Rank            16598
Name            16598
Platform        16598
Year            16327
Genre           16598
Publisher       16540
Global_Sales    16598
dtype: int64

In [614]:
df.dropna(how='any',subset=['Year','Publisher'],inplace=True)

In [615]:
df[df['Publisher'].isnull()]

Empty DataFrame
Columns: [Rank, Name, Platform, Year, Genre, Publisher, Global_Sales]
Index: []

In [616]:
df.isnull().sum()

Rank            0
Name            0
Platform        0
Year            0
Genre           0
Publisher       0
Global_Sales    0
dtype: int64

In [617]:
df.count()

Rank            16291
Name            16291
Platform        16291
Year            16291
Genre           16291
Publisher       16291
Global_Sales    16291
dtype: int64

In [618]:
df.describe()

Rank          Year  Global_Sales
count  16291.000000  16291.000000  16291.000000
mean    8290.190228   2006.405561      0.540910
std     4792.654450      5.832412      1.567345
min        1.000000   1980.000000      0.010000
25%     4132.500000   2003.000000      0.060000
50%     8292.000000   2007.000000      0.170000
75%    12439.500000   2010.000000      0.480000
max    16600.000000   2020.000000     82.740000

In [619]:
#create new column level of global sales
df.loc[df['Global_Sales'].between(10.0,100), 'Sales_level'] = 3
df.loc[df['Global_Sales'].between(1,9.9), 'Sales_level'] = 2
df.loc[df['Global_Sales'].between(0.5377441,0.999), 'Sales_level'] = 1
df.loc[df['Global_Sales'] < 0.5377441, 'Sales_level'] = 0

df.sample(5)


Rank                                            Name Platform    Year  \
6687    6689                                Wheel of Fortune      N64  1997.0   
12845  12847             Lernerfolg Vorschule: Capt'n Sharky       DS  2009.0   
12811  12813  Sled Shred featuring the Jamaican Bobsled Team      Wii  2010.0   
4581    4583                                      Dog's Life      PS2  2003.0   
6623    6625                Romance of the Three Kingdoms II     SNES  1991.0   

           Genre                    Publisher  Global_Sales  Sales_level  
6687        Misc         Take-Two Interactive          0.25          0.0  
12845       Misc                       Tivola          0.05          0.0  
12811     Sports              SouthPeak Games          0.06          0.0  
4581   Adventure  Sony Computer Entertainment          0.42          0.0  
6623    Strategy                   Tecmo Koei          0.25          0.0

In [621]:
#See all Genre
df.Genre.value_counts()

Action          3251
Sports          2304
Misc            1686
Role-Playing    1470
Shooter         1282
Adventure       1274
Racing          1225
Platform         875
Simulation       848
Fighting         836
Strategy         670
Puzzle           570
Name: Genre, dtype: int64

In [622]:
#See all Platform
df.Platform.value_counts()

DS      2131
PS2     2127
PS3     1304
Wii     1290
X360    1234
PSP     1197
PS      1189
PC       938
XB       803
GBA      786
GC       542
3DS      499
PSV      410
PS4      336
N64      316
SNES     239
XOne     213
SAT      173
WiiU     143
2600     116
NES       98
GB        97
DC        52
GEN       27
NG        12
SCD        6
WS         6
3DO        3
TG16       2
GG         1
PCFX       1
Name: Platform, dtype: int64

In [623]:
#Sort platform to num
df.loc[df['Platform'] == 'DS', 'PlatformId'] = 1 
df.loc[df['Platform'] == 'PS2', 'PlatformId'] = 2
df.loc[df['Platform'] == 'PS3', 'PlatformId'] = 3 
df.loc[df['Platform'] == 'Wii', 'PlatformId'] = 4 
df.loc[df['Platform'] == 'X360', 'PlatformId'] = 5 
df.loc[df['Platform'] == 'PSP', 'PlatformId'] = 6 
df.loc[df['Platform'] == 'PS', 'PlatformId'] = 7 
df.loc[df['Platform'] == 'PC', 'PlatformId'] = 8 
df.loc[df['Platform'] == 'XB', 'PlatformId'] = 9
df.loc[df['Platform'] == 'GBA', 'PlatformId'] = 10
df.loc[df['Platform'] == 'GC', 'PlatformId'] = 11
df.loc[df['Platform'] == '3DS', 'PlatformId'] = 12
df.loc[df['Platform'] == 'PSV', 'PlatformId'] = 13
df.loc[df['Platform'] == 'PS4', 'PlatformId'] = 14
df.loc[df['Platform'] == 'N64', 'PlatformId'] = 15
df.loc[df['Platform'] == 'SNES', 'PlatformId'] = 16
df.loc[df['Platform'] == 'XOne', 'PlatformId'] = 17
df.loc[df['Platform'] == 'SAT', 'PlatformId'] = 18
df.loc[df['Platform'] == 'WiiU', 'PlatformId'] = 19
df.loc[df['Platform'] == '2600', 'PlatformId'] = 20
df.loc[df['Platform'] == 'NES', 'PlatformId'] = 21
df.loc[df['Platform'] == 'GB', 'PlatformId'] = 22
df.loc[df['Platform'] == 'DC', 'PlatformId'] = 23
df.loc[df['Platform'] == 'GEN', 'PlatformId'] = 24
df.loc[df['Platform'] == 'NG', 'PlatformId'] = 25
df.loc[df['Platform'] == 'SCD', 'PlatformId'] = 26
df.loc[df['Platform'] == 'WS', 'PlatformId'] = 27
df.loc[df['Platform'] == '3DO', 'PlatformId'] = 28
df.loc[df['Platform'] == 'TG16', 'PlatformId'] = 39
df.loc[df['Platform'] == 'GG', 'PlatformId'] = 30
df.loc[df['Platform'] == 'PCFX', 'PlatformId'] = 31

df.sample(10)


Rank                                               Name Platform  \
14370  14373                                    Starsky & Hutch      GBA   
11178  11180                                 Escape Dead Island     X360   
10968  10970                                Kawasaki Quad Bikes      Wii   
843      845                                      Forza Horizon     X360   
6385    6387  Dora the Explorer: Dora Saves the Crystal Kingdom      Wii   
8398    8400                 Batman Beyond: Return of the Joker       PS   
14219  14222                     Call of Juarez: Bound in Blood       PC   
5718    5720             Sesame Street: Elmo's Letter Adventure       PS   
11151  11153                   Digimon World Re:Digitize Decode      3DS   
9700    9702                          Homefront: The Revolution     XOne   

         Year         Genre                Publisher  Global_Sales  \
14370  2003.0        Racing       Empire Interactive          0.03   
11178  2014.0        Action              Deep Silver          0.09   
10968  2007.0        Racing  Data Design Interactive          0.09   
843    2012.0        Racing   Microsoft Game Studios          2.02   
6385   2009.0          Misc     Take-Two Interactive          0.27   
8398   2000.0        Action                  Ubisoft          0.17   
14219  2009.0       Shooter                  Ubisoft          0.03   
5718   1998.0          Misc                 NewKidCo          0.31   
11151  2013.0  Role-Playing       Namco Bandai Games          0.09   
9700   2016.0       Shooter              Deep Silver          0.12   

       Sales_level  PlatformId  
14370          0.0        10.0  
11178          0.0         5.0  
10968          0.0         4.0  
843            2.0         5.0  
6385           0.0         4.0  
8398           0.0         7.0  
14219          0.0         8.0  
5718           0.0         7.0  
11151          0.0        12.0  
9700           0.0        17.0

In [624]:
#Sort Genre to num
df.loc[df['Genre'] == 'Action', 'GenreId'] = 1 
df.loc[df['Genre'] == 'Sports', 'GenreId'] = 2
df.loc[df['Genre'] == 'Shooter', 'GenreId'] = 3 
df.loc[df['Genre'] == 'Role-Playing', 'GenreId'] = 4 
df.loc[df['Genre'] == 'Misc', 'GenreId'] = 5 
df.loc[df['Genre'] == 'Racing', 'GenreId'] = 6 
df.loc[df['Genre'] == 'Platform', 'GenreId'] = 7 
df.loc[df['Genre'] == 'Fighting', 'GenreId'] = 8 
df.loc[df['Genre'] == 'Simulation', 'GenreId'] = 9 
df.loc[df['Genre'] == 'Puzzle', 'GenreId'] = 10 
df.loc[df['Genre'] == 'Adventure', 'GenreId'] = 11 
df.loc[df['Genre'] == 'Strategy', 'GenreId'] = 12 

df.sample(10)



Rank                                              Name Platform  \
15525  15528          Teenage Mutant Ninja Turtles Double Pack      GBA   
1595    1597      Tom Clancy's Splinter Cell: Pandora Tomorrow      PS2   
7069    7071                                     WWE All Stars      3DS   
5348    5350                UEFA Euro 2008 Austria-Switzerland     X360   
13295  13297                ESPN Great Outdoor Games Bass 2002      GBA   
12581  12583  Teenage Mutant Ninja Turtles 3: Mutant Nightmare       DS   
6676    6678                                            NHL 06       XB   
5480    5482                                NCAA Basketball 10      PS3   
296      297                                       Star Fox 64      N64   
2004    2006                                      Project CARS      PS4   

         Year     Genre                     Publisher  Global_Sales  \
15525  2006.0    Action  Konami Digital Entertainment          0.02   
1595   2004.0    Action                       Ubisoft          1.25   
7069   2011.0  Fighting                           THQ          0.23   
5348   2008.0    Sports               Electronic Arts          0.35   
13295  2001.0    Sports  Konami Digital Entertainment          0.05   
12581  2005.0    Action  Konami Digital Entertainment          0.06   
6676   2005.0    Sports               Electronic Arts          0.25   
5480   2009.0    Sports               Electronic Arts          0.33   
296    1997.0   Shooter                      Nintendo          4.03   
2004   2015.0    Racing          Slightly Mad Studios          1.04   

       Sales_level  PlatformId  GenreId  
15525          0.0        10.0      1.0  
1595           2.0         2.0      1.0  
7069           0.0        12.0      8.0  
5348           0.0         5.0      2.0  
13295          0.0        10.0      2.0  
12581          0.0         1.0      1.0  
6676           0.0         9.0      2.0  
5480           0.0         3.0      2.0  
296            2.0        15.0      3.0  
2004           2.0        14.0      6.0

In [625]:
#Define X and Y
inputs = df.drop('Sales_level',axis='columns')
target = df.Sales_level

In [626]:
# inputs = pd.concat([inputs,GenreId],axis='columns')
# inputs.head(5)


In [627]:
#Drop unused column
inputs.drop(['Rank','Name','Platform','Publisher','Genre','Global_Sales'],axis='columns',inplace=True)
inputs.head()

Year  PlatformId  GenreId
0  2006.0         4.0      2.0
1  1985.0        21.0      7.0
2  2008.0         4.0      6.0
3  2009.0         4.0      2.0
4  1996.0        22.0      4.0

In [628]:
#Define X and Y
X = inputs.astype(int)
Y = target.astype(int)
X_train, X_test, y_train, y_test = train_test_split(X,Y,test_size=0.2)
model = GaussianNB()

In [629]:
X_test[0:10]

Year  PlatformId  GenreId
14905  2007           1       11
11187  2000           7        6
6474   2005           6        6
285    1992          16        8
5762   2015          17        1
15604  2009           1       10
11158  2006           8       12
4729   1999          15        1
2465   2007           4        9
12060  1996           7        9

In [630]:
model.fit(X_train,y_train)

GaussianNB()

In [631]:
model.score(X_test,y_test)

0.7686406873274011

In [632]:
model.predict(X_test[0:10])

array([0, 0, 0, 2, 0, 0, 0, 0, 0, 0])

In [633]:
model.predict_proba(X_test[:10])

array([[9.15600616e-01, 4.86553689e-02, 3.53145762e-02, 4.29439189e-04],
       [7.37978295e-01, 1.21510997e-01, 1.36066687e-01, 4.44402142e-03],
       [8.04433782e-01, 1.03316621e-01, 8.92620000e-02, 2.98759678e-03],
       [3.84584812e-01, 9.32351937e-02, 5.06028310e-01, 1.61516842e-02],
       [6.68466508e-01, 9.01355329e-02, 2.34079823e-01, 7.31813690e-03],
       [8.96394612e-01, 5.85750508e-02, 4.42434859e-02, 7.86851688e-04],
       [9.36321989e-01, 3.77185038e-02, 2.57753229e-02, 1.84184385e-04],
       [6.05425161e-01, 1.12678853e-01, 2.75335032e-01, 6.56095336e-03],
       [8.76252243e-01, 7.04334780e-02, 5.21933328e-02, 1.12094663e-03],
       [7.34046897e-01, 1.10642661e-01, 1.52212771e-01, 3.09767070e-03]])

In [634]:
from sklearn.model_selection import cross_val_score
cross_val_score(GaussianNB(),X_train, y_train, cv=5)

array([0.75949367, 0.75642501, 0.76669225, 0.76745971, 0.75901765])